// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1X7dDuqPHKfyPslJjipsDLfyEuP8CoVI',
    appId: '1:171886106266:web:1d099e0225ffed9ea77123',
    messagingSenderId: '171886106266',
    projectId: 'fluuter-authen',
    authDomain: 'fluuter-authen.firebaseapp.com',
    storageBucket: 'fluuter-authen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMfRTcLEbatWr4C-eXSmNOycp9UmXMRQg',
    appId: '1:171886106266:android:dbcd093ef88d5873a77123',
    messagingSenderId: '171886106266',
    projectId: 'fluuter-authen',
    storageBucket: 'fluuter-authen.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1X7dDuqPHKfyPslJjipsDLfyEuP8CoVI',
    appId: '1:171886106266:web:f24ce6676597dd08a77123',
    messagingSenderId: '171886106266',
    projectId: 'fluuter-authen',
    authDomain: 'fluuter-authen.firebaseapp.com',
    storageBucket: 'fluuter-authen.firebasestorage.app',
  );

}